[[visidata]]
arch = "x86_64"
git-tree-sha1 = "b52d84e03d17cd0bf0c258537d865b43850f09f8"
libc = "glibc"
os = "linux"

    [[visidata.download]]
    sha256 = "ef11749a058e2d8c98dec6477d9b13d3880cde4f59ad2745211db8df9c5ec4bc"
    url = "https://github.com/sandyspiers/Visidata.jl/releases/download/v3.1.1/visidata-linux-x86_64.tar.gz"
[[visidata]]
arch = "x86_64"
git-tree-sha1 = "90024db8bbbbdb2f4f965240b2ec9553594a01d6"
os = "windows"

    [[visidata.download]]
    sha256 = "ea3a41b7b0bbb3707fdb4f0fadcf7e45dd2d2b1e8b6d6a213e84035ab117f9db"
    url = "https://github.com/sandyspiers/Visidata.jl/releases/download/v3.1.1/visidata-windows-x86_64.tar.gz"
