[[visidata]]
arch = "x86_64"
git-tree-sha1 = "c69f622db5f33294f94268dd61adadeb1bf84b6a"
libc = "glibc"
os = "linux"

    [[visidata.download]]
    sha256 = "163719d9b9e8beeb1cabcaa08a726b5c2020556ad3b17e8adfdb0887412445c7"
    url = "https://github.com/sandyspiers/Visidata.jl/releases/download/v3.1.1/visidata-linux-x86_64.tar.gz"
[[visidata]]
arch = "x86_64"
git-tree-sha1 = "af9931b0c0c585728407d8ae93c6cd152324691c"
os = "windows"

    [[visidata.download]]
    sha256 = "700563f1b52c952eb15a377d1c15e2a1a56695fd331547e7be0d8652c3155b3f"
    url = "https://github.com/sandyspiers/Visidata.jl/releases/download/v3.1.1/visidata-windows-x86_64.tar.gz"
